eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: client #这个可以指定client实例对应的url
spring:
  application:
    name: client
  datasource:
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf8&useSSL=false
    username: root
    password: 321asd
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    com:
      springboot:
        dao=debug:
env:
  test3
